---
- hosts: gcp
  gather_facts: yes
  vars:

    zone: us-central1-a
    instance_name: instance-1
    project_id: tidal-surf-250712
    service_account_file: /Users/dan/Downloads/tidal-surf-250712-e8ebb3f4cdb3.json
    timestamp: "{{ ansible_date_time.epoch }}"

  tasks:

  - name: remove a snapshot
    gcp_compute_snapshot:
      name: "{{ instance_name }}-{{ timestamp }}"
      zone: "{{ zone }}"
      project: "{{ project_id }}"
      auth_kind: serviceaccount
      service_account_file: /Users/dan/Downloads/tidal-surf-250712-e8ebb3f4cdb3.json
      state: absent
    register: destroy_task
    delegate_to: localhost
    failed_when: destroy_task.changed == false

  - name: outcome of destroy snapshot task
    debug:
      var: destroy_task
