---

- name: Perform Windows Updates 
  win_updates:
    category_names:
    - CriticalUpdates
    - SecurityUpdates
    state: installed
    log_path: "C:\\Windows\\Temp\\WUpdate.log"
    reboot: yes
    reboot_timeout: 1200 # 20 mins